#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)Makefile.master 1.1 08/07/28 SMI"
#

CFLAGS		=
LDFLAGS		=
COPTFLAG	= -O
LINTFLAGS	= -axsm

include $(SRC)/include/Makefile.common
