#define	MODGETMAJBIND		8
#define	MODSIZEOF_DEVID		10
#define	MODGETDEVID		11
#define	MODSIZEOF_MINORNAME	12
#define	MODGETMINORNAME		13
#define	MODGETFBNAME		16
#define	MODGETDEVFSPATH_LEN	22
#define	MODGETDEVFSPATH		23
#define	MODGETDEVPOLICY		27
#define	MODGETDEVPOLICYBYNAME	29
#define	MODGETDEVFSPATH_MI_LEN	38
#define	MODGETDEVFSPATH_MI	39

#define	MODRETIRE		40
#define	MODUNRETIRE		41
#define	MODISRETIRED		42
