#!/bin/ksh
#ident "@(#)preinstall 1.1 08/04/08 SMI"
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.

if [ ! -d ${BASEDIR} ]
then
	mkdir -p -m 755 ${BASEDIR}
fi
